spring:
  application:
    name: QRMenu
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  jwt:
    secret: ${JWT_SECRET}
twilio:
  sid: ${TWILIO_ACCOUNT_SID}
  token: ${TWILIO_AUTH_TOKEN}